### ISSUE TITLE
Create user model (having name, email and password)

### ISSUE THREAD

**Issue by Bambina-zz** [Bambina/project_x#16]
- [x] マイグレーション作成（name:string email:string password_digest:string）
- [x] ユーザーモデルのemailにインデックス作成
- [x] カラムにnullバリデーションを追加
- [x] gemファイルの要らないコメント削除
- [x] turbolinks gem削除
- [x] bcrypt gem追加

**Comment by Bambina** [comment]
- [] migrationする。（rails g model users name:string email:string）

**Comment by upinetree** [comment]
:+1:
